export const doctors = [
  {
    id: 'doc1',
    name: 'Dr. Evelyn Reed',
    specialization: 'Cardiology',
    bio: 'Dr. Reed is a renowned cardiologist with over 15 years of experience in treating heart conditions. She is a compassionate doctor who is dedicated to providing the best care for her patients.',
    imageUrl: 'https://picsum.photos/400/400',
  },
  {
    id: 'doc2',
    name: 'Dr. John Smith',
    specialization: 'Neurology',
    bio: 'Dr. Smith is a leading neurologist known for his groundbreaking research in neurodegenerative diseases. He is committed to improving the quality of life for his patients through innovative treatments.',
    imageUrl: 'https://picsum.photos/400/400',
  },
  {
    id: 'doc3',
    name: 'Dr. Maria Garcia',
    specialization: 'Pediatrics',
    bio: 'Dr. Garcia is a friendly and experienced pediatrician who loves working with children. She believes in a holistic approach to child health, focusing on both physical and emotional well-being.',
    imageUrl: 'https://picsum.photos/400/400',
  },
    {
    id: 'doc4',
    name: 'Dr. James Brown',
    specialization: 'Orthopedics',
    bio: 'Dr. Brown is a board-certified orthopedic surgeon with expertise in sports medicine and joint replacement. He is dedicated to helping patients regain mobility and return to their active lifestyles.',
    imageUrl: 'https://picsum.photos/400/400',
  },
];

export const appointments = [
    {
        id: "appt1",
        patientName: "Alice Johnson",
        patientEmail: "alice@example.com",
        patientPhone: "1234567890",
        patientAvatar: "https://picsum.photos/200/200?random=1",
        hospitalId: "HOS123",
        age: "34",
        gender: "female",
        doctorId: "doc1",
        doctorName: "Dr. Evelyn Reed",
        doctorAvatar: "https://picsum.photos/200/200?random=2",
        specialty: "Cardiology",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
        time: "10:00 AM",
        roomNumber: "101",
        description: "Annual check-up. No specific symptoms.",
        status: "confirmed",
    },
    {
        id: "appt2",
        patientName: "Bob Williams",
        patientEmail: "bob@example.com",
        patientPhone: "2345678901",
        patientAvatar: "https://picsum.photos/200/200?random=3",
        hospitalId: "HOS456",
        age: "45",
        gender: "male",
        doctorId: "doc2",
        doctorName: "Dr. John Smith",
        doctorAvatar: "https://picsum.photos/200/200?random=4",
        specialty: "Neurology",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
        time: "2:30 PM",
        roomNumber: "205",
        description: "Reason: Persistent headaches. Symptoms: Frequent migraines, sensitivity to light. Allergies: Penicillin.",
        status: "pending",
    },
     {
        id: "appt3",
        patientName: "Charlie Brown",
        patientEmail: "charlie@example.com",
        patientPhone: "3456789012",
        patientAvatar: "https://picsum.photos/200/200?random=5",
        hospitalId: "HOS789",
        age: "28",
        gender: "male",
        doctorId: "doc3",
        doctorName: "Dr. Maria Garcia",
        doctorAvatar: "https://picsum.photos/200/200?random=6",
        specialty: "Pediatrics",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        time: "9:15 AM",
        roomNumber: "112",
        description: "Reason: Flu-like symptoms. Symptoms: Fever, cough, and sore throat.",
        status: "cancelled",
    },
    {
        id: "appt4",
        patientName: "Diana Prince",
        patientEmail: "diana@example.com",
        patientPhone: "4567890123",
        patientAvatar: "https://picsum.photos/200/200?random=7",
        hospitalId: "HOS101",
        age: "31",
        gender: "female",
        doctorId: "doc4",
        doctorName: "Dr. James Brown",
        doctorAvatar: "https://picsum.photos/200/200?random=8",
        specialty: "Orthopedics",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
        time: "11:45 AM",
        roomNumber: "303",
        description: "Follow-up appointment for knee surgery recovery.",
        status: "confirmed",
    },
    {
        id: "appt5",
        patientName: "Edward Norton",
        patientEmail: "edward@example.com",
        patientPhone: "5678901234",
        patientAvatar: "https://picsum.photos/200/200?random=9",
        hospitalId: "HOS202",
        age: "52",
        gender: "male",
        doctorId: "doc1",
        doctorName: "Dr. Evelyn Reed",
        doctorAvatar: "https://picsum.photos/200/200?random=2",
        specialty: "Cardiology",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
        time: "4:00 PM",
        roomNumber: "102",
        description: "Cardiac stress test and consultation.",
        status: "pending",
    }
];
