export const doctors = [
  {
    id: 'doc1',
    name: 'Dr. Evelyn Reed',
    specialization: 'Cardiology',
    bio: 'Dr. Reed is a renowned cardiologist with over 15 years of experience in treating heart conditions. She is a compassionate doctor who is dedicated to providing the best care for her patients.',
    imageUrl: 'https://picsum.photos/400/400',
  },
  {
    id: 'doc2',
    name: 'Dr. John Smith',
    specialization: 'Neurology',
    bio: 'Dr. Smith is a leading neurologist known for his groundbreaking research in neurodegenerative diseases. He is committed to improving the quality of life for his patients through innovative treatments.',
    imageUrl: 'https://picsum.photos/400/400',
  },
  {
    id: 'doc3',
    name: 'Dr. Maria Garcia',
    specialization: 'Pediatrics',
    bio: 'Dr. Garcia is a friendly and experienced pediatrician who loves working with children. She believes in a holistic approach to child health, focusing on both physical and emotional well-being.',
    imageUrl: 'https://picsum.photos/400/400',
  },
    {
    id: 'doc4',
    name: 'Dr. James Brown',
    specialization: 'Orthopedics',
    bio: 'Dr. Brown is a board-certified orthopedic surgeon with expertise in sports medicine and joint replacement. He is dedicated to helping patients regain mobility and return to their active lifestyles.',
    imageUrl: 'https://picsum.photos/400/400',
  },
];

export const appointments = [
    {
        id: "appt1",
        patientName: "Alice Johnson",
        patientEmail: "alice@example.com",
        patientPhone: "1234567890",
        hospitalId: "HOS123",
        age: "34",
        gender: "female",
        doctorId: "doc1",
        doctorName: "Dr. Evelyn Reed",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
        description: "Annual check-up. No specific symptoms.",
        status: "scheduled",
    },
    {
        id: "appt2",
        patientName: "Bob Williams",
        patientEmail: "bob@example.com",
        patientPhone: "2345678901",
        hospitalId: "HOS456",
        age: "45",
        gender: "male",
        doctorId: "doc2",
        doctorName: "Dr. John Smith",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
        description: "Reason: Persistent headaches. Symptoms: Frequent migraines, sensitivity to light. Allergies: Penicillin.",
        status: "scheduled",
    },
     {
        id: "appt3",
        patientName: "Charlie Brown",
        patientEmail: "charlie@example.com",
        patientPhone: "3456789012",
        hospitalId: "HOS789",
        age: "28",
        gender: "male",
        doctorId: "doc3",
        doctorName: "Dr. Maria Garcia",
        appointmentDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        description: "Reason: Flu-like symptoms. Symptoms: Fever, cough, and sore throat.",
        status: "completed",
    }
];
